### ISSUE TITLE
Host projects

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Web-Development#1]
Host via Netlify, Heroku or Vercel, I prefer Netlify, and maybe link them in the portfolio, even if you don't link them in the portfolio I suggest you host it and add links in the README.md of this repo

**Comment by Pradumnasaraf** [comment]
These are notes and for reference purposes, so that's why we need not host them.

Thank you for an opening the issue :)

**Comment by KendallDoesCoding** [comment]
> These are notes and for reference purposes, so that's why we need not host them.
> 
> Thank you for an opening the issue :)

Ok cool :D
